const EmojiCollectorSavedDataTemplate = {
  emojis: [],
  points: 0,
  achievements: [],
  shiny: [],
  stats: {
    avgTimeToClick: 0,
    lastSecClick: 0,
    firstSecClick: 0,
    emojiMissed: 0,
  },
};

const EmojiCollectorData = {
  bugEmoji: {
    emoji: "🐛",
    chance: 0,
    title: "You found a bug, consider reporting :]",
    points: 1,
    rareStatus: 3,
  },
  firstEmoji: "🍪",
  rareStatuses: ['normal', 'rare', 'spacial', 'uniq'],
  emojis: [
    // rare status 0 - 10/20
    {
      emoji: "✌️",
      chance: 200,
      title: "Peace and Love",
      points: 5,
      rareStatus: 0,
    },
    {
      emoji: "🍪",
      chance: 200,
      title: "Clicker",
      points: 5,
      rareStatus: 0,
    },
    {
      emoji: "😍",
      chance: 190,
      title: "Lover",
      points: 7,
      rareStatus: 0,
    },
    {
      emoji: "🤡",
      chance: 190,
      title: "Peanut",
      points: 7,
      rareStatus: 0,
    },
    {
      emoji: "🎃",
      chance: 180,
      title: "PSL",
      points: 10,
      rareStatus: 0,
    },
    {
      emoji: "😼",
      chance: 180,
      title: "Sneaky",
      points: 10,
      rareStatus: 0,
    },
    {
      emoji: "💪",
      chance: 170,
      title: "Lifting",
      points: 15,
      rareStatus: 0,
    },
    {
      emoji: "👮",
      chance: 170,
      title: "Click police",
      points: 15,
      rareStatus: 0,
    },
    {
      emoji: "🧦",
      chance: 160,
      title: "Dirty laundry",
      points: 20,
      rareStatus: 0,
    },
    {
      emoji: "🐭",
      chance: 160,
      title: "Mousing around",
      points: 20,
      rareStatus: 0,
    },
    // rare status 1 - 11/15
    {
      emoji: "🦄",
      chance: 100,
      title: "Majestic",
      points: 50,
      rareStatus: 1,
    },
    {
      emoji: "😀",
      chance: 100,
      title: "OG",
      points: 50,
      rareStatus: 1,
    },
    {
      emoji: "🤩",
      chance: 100,
      title: "Star struck",
      points: 50,
      rareStatus: 1,
    },
    {
      emoji: "🤖",
      chance: 90,
      title: "The Machine",
      points: 50,
      rareStatus: 1,
    },
    {
      emoji: "🐷",
      chance: 90,
      title: "OINK",
      points: 60,
      rareStatus: 1,
    },
    {
      emoji: "🐬",
      chance: 80,
      title: "Free",
      points: 60,
      rareStatus: 1,
    },
    {
      emoji: "🔥",
      chance: 80,
      title: "LIT",
      points: 60,
      rareStatus: 1,
    },
    {
      emoji: "🍆",
      chance: 69,
      title: "...",
      points: 69,
      rareStatus: 1,
    },
    {
      emoji: "🍺",
      chance: 70,
      title: "ANOTHER",
      points: 70,
      rareStatus: 1,
    },
    {
      emoji: "🍬",
      chance: 60,
      title: "Sweet tooth",
      points: 70,
      rareStatus: 1,
    },
    {
      emoji: "🎹",
      chance: 60,
      title: "Tickle me",
      points: 70,
      rareStatus: 1,
    },
    // rare status 2 - 4/10
    {
      emoji: "😎",
      chance: 8,
      title: "Coooool",
      points: 100,
      rareStatus: 2,
    },
    {
      emoji: "🦾",
      chance: 8,
      title: "Upgrades",
      points: 100,
      rareStatus: 2,
    },
    {
      emoji: "🎩",
      chance: 8,
      title: "Fancy-pants",
      points: 100,
      rareStatus: 2,
    },
    {
      emoji: "🍄",
      chance: 8,
      title: "Its-a-me",
      points: 100,
      rareStatus: 2,
    },
    // rare status 3 - 2/5
    {
      emoji: "💸",
      chance: 1,
      title: "Cha-Ching",
      points: 10000,
      rareStatus: 3,
    },
    {
      emoji: "👑",
      chance: 1,
      title: "Royalty",
      points: 10000,
      rareStatus: 3,
    },
  ],
  achievements: [
    {
      condition: {
        check: "points",
        for: 100,
      },
      text: "On the board - winning 100 points",
      icon: "🥉",
    },
    {
      condition: {
        check: "emojis",
        type: "🍪",
        for: 10,
      },
      text: "Master-baker - collecting 10 cookies",
      icon: "🍪",
    },
    {
      condition: {
        check: "types",
        for: 10,
      },
      text: "Slowly but surely - collecting 10 different types",
      icon: "☝️",
    },
  ],
};
